#!/usr/bin/env bash
#
# install.sh — set up a working JARVIS + LLM gateway on a fresh machine.
#
# This mirrors the author's own setup: the JARVIS agent routed through an
# OmniRoute LLM gateway, with the optional Gmail/browser/computer extras and
# the SKILL.md library. It needs no account and commits no secrets.
#
# Usage:
#   ./install.sh                     core install (venv + JARVIS + OmniRoute + skills)
#   ./install.sh --no-omniroute      keep your own LLM gateway (edit .env after)
#   ./install.sh --no-skills         skip the ~500 MB SKILL.md collection
#   ./install.sh --all               also install gmail + browser + computer extras
#   ./install.sh --extras "gmail,browser,computer"
#   ./install.sh --no-verify         skip the end-of-install health check
#   ./install.sh -h                  this help
#
# Env overrides: PYTHON, JARVIS_INSTALL_DIR (run from a parent dir), and the
# flags can also be set as SKIP_OMNIROUTE=1 / SKIP_SKILLS=1 / EXTRAS="...".
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${JARVIS_INSTALL_DIR:-$SCRIPT_DIR}"
cd "$PROJECT_DIR"

# ---------------------------------------------------------------------------
# Configurable defaults
# ---------------------------------------------------------------------------
BRANCH="${JARVIS_INSTALL_BRANCH:-main}"
INSTALL_OMNIROUTE=1
INSTALL_SKILLS=1
VERIFY=1
EXTRAS=""
PYTHON="${PYTHON:-python3}"
OMNIROUTE_PORT="${OMNIROUTE_PORT:-20128}"

# Allow env-based flags in addition to CLI flags.
[[ "${SKIP_OMNIROUTE:-0}" == "1" ]] && INSTALL_OMNIROUTE=0
[[ "${SKIP_SKILLS:-0}" == "1" ]] && INSTALL_SKILLS=0
[[ -n "${EXTRAS_ENV:-}" ]] && EXTRAS="$EXTRAS_ENV"

show_help() { sed -n '2,26p' "$0"; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-omniroute) INSTALL_OMNIROUTE=0; shift ;;
        --no-skills)    INSTALL_SKILLS=0;  shift ;;
        --no-verify)    VERIFY=0;          shift ;;
        --all)          EXTRAS="gmail,browser,computer"; shift ;;
        --extras)       EXTRAS="$2"; shift 2 ;;
        --extras=*)     EXTRAS="${1#*=}"; shift ;;
        --branch)       BRANCH="$2"; shift 2 ;;
        --branch=*)     BRANCH="${1#*=}"; shift ;;
        -h|--help)      show_help; exit 0 ;;
        *) echo "Unknown argument: $1 (see $0 --help)" >&2; exit 2 ;;
    esac
done

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
have() { command -v "$1" >/dev/null 2>&1; }
die() { echo "ERROR: $*" >&2; exit 1; }
step() { printf '\n==> %s\n' "$*"; }
ok()   { printf '    done: %s\n' "$*"; }

section() {
    echo
    echo "================================================================"
    echo "  $1"
    echo "================================================================"
}

section "JARVIS installer"
echo "  project: $PROJECT_DIR"
echo "  python:  $PYTHON"
echo "  branch:  $BRANCH"
echo "  omniroute: $([ "$INSTALL_OMNIROUTE" -eq 1 ] && echo yes || echo 'no (use existing gateway)')"
echo "  skills:  $([ "$INSTALL_SKILLS" -eq 1 ] && echo 'yes (~500 MB)' || echo no)"
echo "  extras:  ${EXTRAS:-none}"

# ---------------------------------------------------------------------------
# 0. Prerequisites
# ---------------------------------------------------------------------------
step "Checking prerequisites"
have "$PYTHON"      || die "Python not found ('$PYTHON'). Install Python >= 3.10."
"$PYTHON" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' \
    || die "Python >= 3.10 required (found $($PYTHON --version 2>&1))."
have git            || die "'git' not found. Install git (apt/brew/pkg/...)."
have curl           || die "'curl' not found. Install curl."
have "$PYTHON"       && ok "python $($PYTHON --version 2>&1), git, curl"

if [ "$INSTALL_OMNIROUTE" -eq 1 ]; then
    { have node && have npm; } || die "Node.js + npm required to install OmniRoute ($OMNIROUTE_PORT). Use nvm or your package manager."
    ok "node $(node --version 2>&1), npm $(npm --version 2>&1)"
fi

# Ensure the venv tooling is present (python3-venv on Debian/Ubuntu).
if ! "$PYTHON" -m venv --help >/dev/null 2>&1; then
    die "The '$PYTHON' interpreter cannot create venvs (missing python3-venv)."
fi

# ---------------------------------------------------------------------------
# 1. Environment files (.env, config/config.yaml, data/profile.yaml)
# ---------------------------------------------------------------------------
step "Environment files (created only if missing — never overwritten)"
mkdir -p config data

ENV_FILE="$PROJECT_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    ok ".env exists — not overwriting (edit it to adjust the gateway)"
else
    cat > "$ENV_FILE" <<EOF
# JARVIS environment — generated by install.sh. .env is gitignored.
JARVIS_LLM_BASE_URL=http://127.0.0.1:${OMNIROUTE_PORT}/v1
JARVIS_LLM_API_KEY=
JARVIS_MODEL_FAST=auto/fast
JARVIS_MODEL_REASONING=auto/reasoning
JARVIS_MODEL_VISION=auto/vision
JARVIS_GMAIL_CREDENTIALS=data/gmail-credentials.json
JARVIS_GMAIL_TOKEN=data/gmail-token.json
JARVIS_SAFETY_MODE=interactive
EOF
    ok "created .env (OmniRoute on 127.0.0.1:${OMNIROUTE_PORT}, auto/reasoning agent)"
fi

CFG="$PROJECT_DIR/config/config.yaml"
if [ -f "$CFG" ]; then
    ok "config/config.yaml exists — not overwriting"
elif [ -f "$PROJECT_DIR/config/config.example.yaml" ]; then
    cp "$PROJECT_DIR/config/config.example.yaml" "$CFG"
    ok "created config/config.yaml from example"
else
    ok "no config example found — JARVIS defaults apply"
fi

PROFILE="$PROJECT_DIR/data/profile.yaml"
if [ -f "$PROFILE" ]; then
    ok "data/profile.yaml exists — not overwriting"
else
    printf 'name: ""\nemail: ""\nlocation: ""\npreferred_roles: []\n' > "$PROFILE"
    ok "created blank data/profile.yaml"
fi

# ---------------------------------------------------------------------------
# 2. Python virtual environment + JARVIS
# ---------------------------------------------------------------------------
step "Python virtual environment"
VENV="$PROJECT_DIR/.venv"
if [ ! -x "$VENV/bin/python" ]; then
    "$PYTHON" -m venv "$VENV"
    ok "created venv at $VENV"
else
    ok "venv already exists at $VENV"
fi

VENV_PY="$VENV/bin/python"
VENV_PIP="$VENV/bin/pip"
"$VENV_PY" -m pip install --upgrade pip >/dev/null
ok "pip $("$VENV_PIP" --version 2>&1 | awk '{print $2}')"

step "Installing JARVIS ($([ -n "$EXTRAS" ] && echo "extras: [$EXTRAS]" || echo core))"
if [ -n "$EXTRAS" ]; then
    "$VENV_PIP" install --quiet -e ".[$EXTRAS]"
else
    "$VENV_PIP" install --quiet -e .
fi
[ -x "$VENV/bin/jarvis" ] || die "JARVIS console script missing after install."
ok "jarvis CLI at $VENV/bin/jarvis"

# Optional heavy runtime setup for specific extras.
if [[ ",$EXTRAS," == *,browser,* ]]; then
    step "Browser extra: installing Playwright Chromium"
    "$VENV_PY" -m playwright install chromium >/dev/null 2>&1 \
        || echo "    note: 'playwright install chromium' failed — run it later if you use browser tools."
    ok "playwright chromium"
fi
if [[ ",$EXTRAS," == *,gmail,* ]]; then
    step "Gmail extra"
    echo "    To use the email engine, place your Google OAuth client secret at"
    echo "    data/gmail-credentials.json, then run:  $VENV/bin/jarvis email digest"
fi

# ---------------------------------------------------------------------------
# 3. OmniRoute gateway
# ---------------------------------------------------------------------------
if [ "$INSTALL_OMNIROUTE" -eq 1 ]; then
    step "OmniRoute LLM gateway"
    if have omniroute; then
        ok "omniroute already installed: $(command -v omniroute)"
    else
        echo "Installing global npm package 'omniroute'..."
        if npm install -g omniroute; then
            ok "omniroute installed"
        else
            echo "ERROR: 'npm install -g omniroute' failed." >&2
            echo "       Common causes: no permission (use nvm, or a user-level npm" >&2
            echo "       prefix), or Node is too old. Install manually and re-run." >&2
            exit 1
        fi
    fi
else
    step "Skipping OmniRoute install (--no-omniroute)."
    echo "Set JARVIS_LLM_BASE_URL (and optionally JARVIS_LLM_API_KEY) in $PROJECT_DIR/.env to your own OpenAI-compatible endpoint."
fi

# ---------------------------------------------------------------------------
# 4. SKILL.md library (optional, large)
# ---------------------------------------------------------------------------
if [ "$INSTALL_SKILLS" -eq 1 ]; then
    step "SKILL.md library (~500 MB, one-time)"
    echo "Cloning the Luo-Kai SKILL.md aggregation repo..."
    "$VENV/bin/jarvis" skills install
    ok "skill library installed"
else
    step "Skipping SKILL.md library (--no-skills)."
    echo "Install later with:  $VENV/bin/jarvis skills install"
fi

# ---------------------------------------------------------------------------
# 5. Verify
# ---------------------------------------------------------------------------
if [ "$VERIFY" -eq 1 ]; then
    step "Verifying installation"
    # Start the gateway (no-op if already running) then run JARVIS diagnostics.
    if [ "$INSTALL_OMNIROUTE" -eq 1 ]; then
        "$PROJECT_DIR/start.sh" --no-llm doctor || true
    else
        "$VENV/bin/jarvis" doctor || true
    fi
    echo
    echo "If the LLM gateway shows 'unreachable', start it with:" 
    echo "    $PROJECT_DIR/start.sh"
    echo "then re-run: $VENV/bin/jarvis doctor"
fi

# ---------------------------------------------------------------------------
# 6. Done
# ---------------------------------------------------------------------------
section "Installation complete"
echo
echo "Run the chat UI:      $PROJECT_DIR/start.sh"
echo "One-shot question:    $PROJECT_DIR/start.sh ask \"...\""
echo "Health check:         $PROJECT_DIR/start.sh doctor"
echo "Manage skills:        $VENV/bin/jarvis skills --help"
echo
echo "Manual config lives in $PROJECT_DIR/.env and $PROJECT_DIR/config/config.yaml."
echo "Gmail setup:          place data/gmail-credentials.json then 'jarvis email digest'."
echo "Safety mode:          .env JARVIS_SAFETY_MODE (interactive | auto | yolo)."
